# File: pubspec.yaml

name: gestib
description: "Una aplicación de gestograma para calcular la fecha de parto"

publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.3
  # Descomenta si decides usarlo y lo añades como dependencia:
  # flutter_native_timezone_updated_gradle: ^2.0.4 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/gestib_icon.png
    - assets/fetal_development/ # Asegúrate que esta línea termine con una barra /

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/gestib_icon.png"
  min_sdk_android: 21